# -*- coding: utf-8 -*-
"""zadanie2pwjwp2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16btN5jZ68OG3jQMFs92BREtjelrQDpPF
"""

class TextAnalyzer():
    def word_count(self,text):
        x = text.split(' ')
        return len(x)
    def char_cout(self,text):
        x = text.split(' ')
        y=''
        for i in x:
            y=y+i
        return len(y)
    def unique_words(self,text):
        x = text.split(' ')
        return len(set(x))

class AdvancedTextAnalyzer(TextAnalyzer):
    def sentiment_analysis(self,text):
        pozytywne = ["wspaniały", "super", "mega"]
        negatywne = ["okropny", "słaby", "beznadziejny"]
        neutralne = ["ciekawy", "kuriozalny", "nietypowy"]
        x = text.split(' ')
        for i in pozytywne:
            if i in x:
                return "pozytywny"
        for i in negatywne:
            if i in x:
                return "negatywny"
        for i in neutralne:
            if i in x:
                return "neutralny"
        return "???"

ta = TextAnalyzer()
taa = AdvancedTextAnalyzer()
seq = "bialy kot i czarny kot ida do lasu"
seq2 = "To był naprawdę wspaniały dzień!"
seq3 = "To był naprawdę okropny dzień!"
print(ta.word_count(seq))

print(ta.char_cout(seq))

print(ta.unique_words(seq))

print(ta.word_count(seq2))

print(ta.char_cout(seq2))

print(ta.unique_words(seq2))

print(taa.sentiment_analysis(seq2))

print(taa.sentiment_analysis(seq3))